"""Real-time captioning engine.

Captures audio from a microphone (sounddevice) or from system output audio
(WASAPI loopback via PyAudioWPatch), then transcribes accumulated windows with
Whisper on a background thread. Results are exposed as an append-only queue of
:class:`Caption` that the UI drains.

This module renders no Streamlit elements so it can be unit-tested and reused.

Sources: ``source="mic"`` (microphone) or ``source="system"`` (loopback of the
audio the machine is currently playing).
"""

from __future__ import annotations

import queue
import re
import threading
import time
import traceback
from dataclasses import dataclass, replace
from pathlib import Path

import numpy as np

from han_convert import is_chinese_lang, to_simplified_if_chinese

TARGET_SR = 16_000

# Whisper 的 initial_prompt 上限约 224 token：按字符粗截（超长模型会报错）。
_MAX_PROMPT_CHARS = 200

# 静音/噪声窗里 Whisper 特别爱"翻译"出来的片尾字幕。它们还自带**高置信度**的语种
# 声明 —— 拿它们当语种证据，中文音频会被一票钉成日语（然后整场都在用日语解码，
# 出来就是错乱）。判断只看归一化后的整句，避免误伤真说了"字幕"两个字的内容。
_FILLER_TEXTS = {
    "you", "thanks for watching", "thank you.", "thank you", "yeah.", "yeah",
    "ok.", "ok", "by", ".", "…", "...", "*",
    "好的。", "好的", "谢谢观看", "谢谢大家", "广告", "字幕", "请欣赏", "下一集",
    "字幕由 amara.org 社区提供", "字幕由 Amara.org 社区提供",
    "本视频字幕由 Amara.org 社群提供",
}
_HALLUCINATIONS = {
    "日本語字幕", "日本字幕", "ご視聴ありがとうございました", "ありがとうございました",
    "subtitles by", "subtitle by", "subs by", "amara.org", "amara", "amaraorg",
    "www.amara.org", "字幕by", "字幕组", "本字幕由 volunteership 编写",
}
# 假名（平/片/半角片假名）：日语硬证据；汉字：中日共用，需要配合假名才判得准
_KANA_RE = re.compile("[\u3040-\u30ff\u31f0-\u31ff]")
_HANZI_RE = re.compile("[\u4e00-\u9fff\uf900-\ufaff\u3400-\u4dbf]")
_LATIN_RE = re.compile("[A-Za-z]")
_PUNCT_RE = re.compile(r"[\\s.,!?;:\u3002\u3001\u2026~\u301c\u30fb\-]+")   # 空白/中英标点都算噪声，只留文字

# 语种投票的三个阈值（都是在这台机器的真实音频上试出来的）
_VOTE_MIN_CONF = 0.45        # 低于这个置信度的声明直接不算票（日语短窗常报 0.5 左右）
_SCRIPT_CONF = 0.80          # 文字脚本证据的等价置信度：假名/汉字几乎不会骗人
_SCRIPT_OVERRIDES_ZH = 0.90    # "汉字无假名"日语也可能长这样，模型自报不到 0.9 才让脚本抢
                             # （假名是硬证据，任何置信度都直接判日语）
_CJK_PAIR = {"zh", "ja"}     # 中文↔日语是最容易互翻的一对，切换要更多票
_LANG_NAMES = {"zh": "中文", "ja": "日本語", "en": "English", "yue": "粤语",
             "ko": "한국어", "fr": "Français", "de": "Deutsch", "es": "Español"}


def _norm_text(text: str) -> str:
    """去空格去标点、小写 —— 给"整句是不是幻觉片尾"这类判断用。"""
    return _PUNCT_RE.sub("", (text or "").lower())


def is_hallucinated(text: str) -> bool:
    """整句就是 Whisper 在静音里编的片尾字幕（或短到没有信息量）。"""
    t = _norm_text(text)
    if not t:
        return True
    if t in _FILLER_TEXTS or _norm_text(t) in _HALLUCINATIONS:
        return True
    # 「...字幕」「...generated by ...」这种尾巴形态：短且以片尾词收尾
    if len(t) <= 12 and (t.endswith("字幕") or t.endswith("字幕by")
                         or t.endswith("subtitles") or t.endswith("amaraorg")):
        return True
    return False


def script_language(text: str) -> str | None:
    """只看文字本身猜语种：有假名→ja，汉字为主→zh，拉丁词为主→en，看不出→None。

    为什么值得单独做：faster-whisper 的 language_probability 在 4 秒短窗上很不稳
    （日语经常 0.5、紧跟一个 zh），但"这句里有没有假名"是几乎不会骗人的硬证据。
    """
    if not text:
        return None
    kana = len(_KANA_RE.findall(text))
    han = len(_HANZI_RE.findall(text))
    if kana >= 2:
        return "ja"                      # 中文里不会出现假名
    if kana == 0 and han >= 2:
        return "zh"
    latin = len(_LATIN_RE.findall(text))
    if kana == 0 and han == 0 and latin >= 4 and len(text.split()) >= 3:
        return "en"
    return None

@dataclass
class Caption:
    """One recognized utterance."""

    index: int
    start: float  # seconds on the audio clock, measured from session start
    end: float
    text: str
    wall_clock: float  # unix timestamp when the text was produced

    @property
    def label(self) -> str:
        return time.strftime("%H:%M:%S", time.localtime(self.wall_clock))


def resample_to_16k(audio: np.ndarray, source_sr: int) -> np.ndarray:
    """Linear resample a 1-D float32 buffer to ``TARGET_SR``."""
    if source_sr == TARGET_SR or audio.size == 0:
        return audio.astype(np.float32, copy=False)
    duration = audio.shape[0] / float(source_sr)
    target_len = max(int(round(duration * TARGET_SR)), 1)
    src_idx = np.linspace(0.0, audio.shape[0] - 1, num=audio.shape[0])
    dst_idx = np.linspace(0.0, audio.shape[0] - 1, num=target_len)
    return np.interp(dst_idx, src_idx, audio).astype(np.float32)


# ------------------------------------------------------ 半句缝合（原位修订）
# 早触发（停顿 0.6 秒就提前送检）换来低延迟，代价是一句话常被切成两条：
#     "They must move." + "As one."             → 应为 They must move as one.
#     "They are fighting" + "for access to…"    → 应为 …fighting for access to…
# 判"说完没"不能靠标点——Whisper 会给每个窗口都补一个句号。这里改靠词法线索：
#   A) 下一条以"几乎不可能开启新句"的接续词开头（as/for/to/of/and/but/that/which…）
#   B) 上一条以**悬空词**收尾（冠词/介词/助动词/物主代词，或以逗号收尾）
# 命中 A 或 B 就把后条并进前条，并且**沿用前条的条目号**重新发布（store 的 rev+1）：
# 网页与悬浮窗原位改成整句、译文跟着重出——首条显示零延迟，也不会多出一条半句。
_CONTINUERS = frozenset("""
as and but or nor for to of in on at by with from into onto over under that which who whom whose
because since while after before until than so if then not no all any some each every more most
much many own same very just only even also too again ever never always still yet though
is are was were be been being have has had do does did will would can could should may might must
""".split())

def write_wav_mono16(path: str | Path, audio: np.ndarray) -> None:
    """把 float32 单声道写成 16k/16bit WAV（只用标准库 wave，不引新依赖）。"""
    import wave

    data = (np.clip(np.asarray(audio, dtype=np.float64).ravel(), -1.0, 1.0)
            * 32767.0).astype("<i2").tobytes()
    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(TARGET_SR)
        wf.writeframes(data)


def read_wav_mono16(path: str | Path) -> np.ndarray:
    """读回 float32（精修重识别用；只认我们自己写的 16k 单声道格式）。"""
    import wave

    with wave.open(str(path), "rb") as wf:
        if wf.getnchannels() != 1 or wf.getsampwidth() != 2:
            raise ValueError(f"{path} 不是 16bit 单声道 WAV")
        raw = wf.readframes(wf.getnframes())
    return np.frombuffer(raw, dtype="<i2").astype(np.float32) / 32768.0


# 上一条以这些词收尾 → 句子必然没说完（在 _CONTINUERS 之外补上冠词/物主代词等）
_DANGLERS = _CONTINUERS | frozenset("""
a an the my your his her its our their this these those both such enough
""".split())

_HARD_END = frozenset("!?…⋯？！。")      # 真正的句尾，绝不并
_SOFT_TAIL = " \t.,;:，、；：”’）)】]"   # 合并时从上一条尾部剥掉的软标点
_WORD_RE = re.compile(r"[0-9A-Za-z\u00c0-\u024f']+")


def _has_words(text: str) -> bool:
    """缝合只对**空格分词**的语种有意义：中文没有词边界，按词判接续必乱。"""
    return bool(re.search(r"[A-Za-z\u00c0-\u024f]", text or ""))


def _tail_punct(text: str) -> str:
    m = re.search(r"\W+$", text or "")
    return m.group() if m else ""


def _first_word(text: str) -> str:
    m = _WORD_RE.search(text or "")
    return m.group(0).lower() if m else ""


def _last_word(text: str) -> str:
    ws = _WORD_RE.findall(text or "")
    return ws[-1].lower() if ws else ""


def is_hard_ended(text: str) -> bool:
    """是否以 !?。！？… 收尾（真句尾 → 不参与缝合）。"""
    return any(c in _HARD_END for c in _tail_punct(text))


def stitch_texts(prev: str, nxt: str, *, max_prev: int = 80,
                 max_merged: int = 160) -> str | None:
    """能并成整句就返回合并结果，否则返回 None。纯函数，便于单测。"""
    prev = (prev or "").strip()
    nxt = (nxt or "").strip()
    if not prev or not nxt or len(prev) > max_prev:
        return None
    if not (_has_words(prev) and _has_words(nxt)):
        return None
    if is_hard_ended(prev):
        return None
    tail = _tail_punct(prev)
    # 只凭"尾部没标点"不足以判成断句（电报式短句会被误并），必须有词法线索
    dangling = _last_word(prev) in _DANGLERS or "," in tail or ";" in tail
    continues = _first_word(nxt) in _CONTINUERS
    if not (dangling or continues):
        return None
    head = prev.rstrip(_SOFT_TAIL)
    body = nxt
    # 接续词开头统一小写：Whisper 给每条都打大写，"As one." 并回来应为 "as one."
    if continues:
        m = _WORD_RE.match(body)
        if m:
            body = body[:m.start()] + m.group(0).lower() + body[m.end():]
    merged = " ".join((head + " " + body).split())
    return merged if len(merged) <= max_merged else None


class SentenceStitcher:
    """把被窗口/停顿切断的半句**原位修订**成整句（不推迟首条显示）。"""

    def __init__(self, *, enabled: bool = True, max_gap: float = 6.0,
                 max_prev: int = 80, max_merged: int = 160) -> None:
        self.enabled = bool(enabled)
        self.max_gap = float(max_gap)
        self.max_prev = int(max_prev)
        self.max_merged = int(max_merged)
        self.pending: Caption | None = None
        self.merges = 0        # 缝合次数（状态行/测试用）

    def reset(self) -> None:
        self.pending = None

    def offer(self, cap: Caption) -> Caption:
        """返回该发布的字幕：新条目，或**同一条目号的修订版**（半句并回上一条）。"""
        if not self.enabled:
            return cap
        prev = self.pending
        if prev is not None and cap.wall_clock - prev.wall_clock <= self.max_gap:
            merged = stitch_texts(prev.text, cap.text, max_prev=self.max_prev,
                                  max_merged=self.max_merged)
            if merged:
                revised = replace(prev, text=merged, end=cap.end,
                                  wall_clock=cap.wall_clock)
                self.pending = revised
                self.merges += 1
                return revised
        self.pending = cap
        return cap


class CaptionEngine:
    """Microphone or system-loopback -> Whisper real-time caption pipeline.

    The engine is owned by a single Streamlit session (stored in
    ``st.session_state``), never at module import scope.
    """

    def __init__(
        self,
        model,
        *,
        device=None,
        source: str = "mic",
        loopback_device=None,
        chunk_seconds: float = 4.0,
        language: str | None = None,
        silence_rms: float = 0.005,
        max_buffered_seconds: float = 12.0,
        initial_prompt: str | None = None,
        flush_after_silence: float = 0.6,
        stitch_fragments: bool = True,
        vad_probe: bool = True,
        probe_interval: float = 1.0,
        probe_len: float = 1.4,
        record: bool = False,
        record_dir: str | Path = "records",
        auto_unfilter: bool = True,
        simplify: bool = True,        # 中文一律输出简体（繁体口音/后端常给繁体）
    ) -> None:
        self.model = model
        self.device = device
        self.source = source
        self.loopback_device = loopback_device
        self.chunk_seconds = float(chunk_seconds)
        self.language = language
        self.silence_rms = float(silence_rms)
        self.max_buffered_samples = int(max_buffered_seconds * TARGET_SR)
        self.initial_prompt = (initial_prompt or "")[:_MAX_PROMPT_CHARS].strip() or None
        self.flush_after_silence = float(flush_after_silence)
        # 半句缝合：把早触发切出来的后半句并回上一条（同条目号 = 原位修订）
        self.stitcher = SentenceStitcher(enabled=stitch_fragments)
        self._auto_language = language is None
        self._last_voice_at = time.time()
        self._vad_supported = False     # 是否至少见过一次 speech_end（后端能力探测）
        self._voice_observed = False    # 本轮是否确认过语音，未确认前不早触发

        # ② VAD 探针：用"探测级解码"的语音段结果判断是否停顿——专治 BGM 下
        #    RMS 永远高于门限、早触发从不生效的问题。③ 同一次探测顺带投票
        #    语种，实现识别中途换语言时的自动重钉（仅"自动检测"模式）。
        self.vad_probe = bool(vad_probe)
        self.probe_interval = float(probe_interval)
        self.probe_len = float(probe_len)
        self._last_probe_at = 0.0
        self._lang_votes: list[str] = []
        self.detected_language = ""       # 最近一次检测/投票胜出的语种
        self.language_switches = 0        # 自动切换语种的次数（UI toast 用）
        self.notice = ""                  # 一次性提示（"语种自动切换：ja"）
        self.notice_at = 0.0              # 提示产生时刻（UI 端 6 秒后不再显示）

        self._audio_q: queue.Queue = queue.Queue()
        self._results: queue.Queue = queue.Queue()
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None
        self._stream = None
        self._pa = None
        self._pa_mod = None
        self._lb_channels = 1
        self._lock = threading.Lock()

        self.source_sr = TARGET_SR
        self.started_at = 0.0
        self.error = ""
        self.hint = ""                # 非致命提示（如"未检测到音频信号"）
        self.last_rms = 0.0
        self.rx_blocks = 0            # 收到的回调块数（判断是否真的有数据流）
        self.last_audio_at = 0.0      # 最近一次收到数据的时间
        self.processed_chunks = 0
        self.dropped_samples = 0
        self.thread_errors = 0      # 识别线程被异常打断的次数（界面状态行可见）
        self.auto_unfilter = bool(auto_unfilter)  # 有声零字时自动关掉非语音过滤
        self.empty_windows = 0      # 连续「有音量但模型给零字」的窗数
        self.filter_disabled = False              # 非语音过滤是否已被自动关掉
        self.simplify = bool(simplify)            # 中文轨道强制简体
        self.last_sound_at = 0.0   # 最近一次"电平过门限"的时刻（判断纯静音）
        self.decoding_at = 0.0      # 当前这窗开始解码的时刻（0 = 没在解）
        self.decoding_span = (0.0, 0.0)   # 在解哪一段音频（秒）
        self.decoding_probe = False
        self.thread_error_log: list[str] = []   # 栈尾若干条，卡住时能直接看见原因
        self._buffer: list[np.ndarray] = []
        self._buffered_samples = 0
        self._consumed_samples = 0
        self._seq = 0

        # 录音留档：给"停止后整篇精修重识别"用。写的是**送进模型之前**的那份
        # 16k 单声道原始音频（不受静音门/背压丢弃影响），所以精修能看到被实时
        # 链路丢掉的音频。
        self.record_enabled = bool(record)
        self.record_dir = record_dir
        self.record_path = ""        # 本轮录音文件路径（"" = 没录）
        self.recorded_samples = 0
        self.record_error = ""
        self._rec = None             # wave 文件句柄（只在消费者线程写）

    # ------------------------------------------------------------------ API
    @property
    def running(self) -> bool:
        return self._thread is not None and self._thread.is_alive()

    @property
    def backlog_seconds(self) -> float:
        """Audio still waiting to be transcribed (grows if the model is too slow)."""
        return self._buffered_samples / TARGET_SR

    def start(self) -> bool:
        """Open the capture source and start the transcription thread."""
        if self.running:
            return True
        self._open_recorder()
        ok = self._start_loopback() if self.source == "system" else self._start_mic()
        if not ok:
            self._close_recorder()
        return ok

    def stop(self, *, flush: bool = True) -> None:
        """Stop capture, optionally transcribing whatever is still buffered."""
        self._stop.set()
        if self.source == "system":
            self._close_loopback()
        else:
            self._close_stream()
        thread = self._thread
        self._thread = None
        if thread is not None and thread.is_alive():
            thread.join(timeout=5.0)
        # 停止后队列里可能仍有残留块，清掉避免混入下一次会话。
        while True:
            try:
                self._audio_q.get_nowait()
            except queue.Empty:
                break
        if flush:
            self._drain_buffer(force=True)
        self._close_recorder()

    def drain(self, limit: int = 200) -> list[Caption]:
        """Return and remove pending captions (most recent last)."""
        items: list[Caption] = []
        while len(items) < limit:
            try:
                items.append(self._results.get_nowait())
            except queue.Empty:
                break
        return items

    def elapsed(self) -> float:
        if not self.started_at:
            return 0.0
        return time.time() - self.started_at

    # ------------------------------------------------------------- mic path
    def _start_mic(self) -> bool:
        import sounddevice as sd

        self._stop.clear()
        self.error = ""
        self._buffer.clear()
        self._buffered_samples = 0
        self._consumed_samples = 0
        self.started_at = time.time()
        self._reset_run_state()

        info = sd.query_devices(self.device, kind="input")
        self.source_sr = int(round(info["default_samplerate"])) or TARGET_SR
        channels = min(1, int(info["max_input_channels"])) or 1

        try:
            self._stream = sd.InputStream(
                samplerate=self.source_sr,
                blocksize=0,
                channels=channels,
                dtype="float32",
                device=self.device,
                callback=self._on_audio,
            )
            self._stream.start()
        except Exception as exc:  # noqa: BLE001
            self._close_stream()
            self.error = f"无法打开麦克风：{exc}"
            return False

        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        return True

    # ----------------------------------------------------- loopback (system)
    def _start_loopback(self) -> bool:
        try:
            import pyaudiowpatch as pyaudio
        except Exception as exc:  # noqa: BLE001
            self.error = f"未安装 PyAudioWPatch：pip install PyAudioWPatch（{exc}）"
            return False

        self._pa_mod = pyaudio
        try:
            self._pa = pyaudio.PyAudio()
            if self.loopback_device is None:
                dev = self._pa.get_default_wasapi_loopback()
            else:
                dev = self._pa.get_device_info_by_index(int(self.loopback_device))
            rate = int(dev["defaultSampleRate"] or 48_000)
            channels = int(dev["maxInputChannels"] or 1)

            self._stop.clear()
            self.error = ""
            self._buffer.clear()
            self._buffered_samples = 0
            self._consumed_samples = 0
            self.started_at = time.time()
            self._reset_run_state()
            self.source_sr = rate
            self._lb_channels = channels

            # 用回调流而不是阻塞 read()：WASAPI loopback 在静音时不产生
            # 数据包，阻塞 read() 会永久卡住。
            self._stream = self._pa.open(
                format=pyaudio.paFloat32,
                channels=channels,
                rate=rate,
                input=True,
                input_device_index=dev["index"],
                frames_per_buffer=int(rate * 0.1),
                stream_callback=self._on_loopback,
            )
            self._stream.start_stream()
        except Exception as exc:  # noqa: BLE001
            self._close_loopback()
            self.error = f"无法打开系统声音回环：{exc}"
            return False

        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        return True

    def _close_loopback(self) -> None:
        stream, self._stream = self._stream, None
        if stream is not None:
            try:
                stream.stop_stream()
            except Exception:  # noqa: BLE001
                pass
            try:
                stream.close()
            except Exception:  # noqa: BLE001
                pass
        pa, self._pa = self._pa, None
        if pa is not None:
            try:
                pa.terminate()
            except Exception:  # noqa: BLE001
                pass

    # ------------------------------------------------------------ internals
    # ------------------------------------------------------------- 录音留档
    def _open_recorder(self) -> None:
        """按需打开本轮的 16k 单声道 WAV（record=False 或已在跑就不动）。"""
        self._close_recorder()
        self.recorded_samples = 0
        self.record_error = ""
        self.record_path = ""
        if not self.record_enabled:
            return
        try:
            import wave
            from datetime import datetime

            d = Path(self.record_dir)
            d.mkdir(parents=True, exist_ok=True)
            self.record_path = str(d / ("session-%s.wav"
                                        % datetime.now().strftime("%Y%m%d-%H%M%S")))
            self._rec = wave.open(self.record_path, "wb")
            self._rec.setnchannels(1)
            self._rec.setsampwidth(2)
            self._rec.setframerate(TARGET_SR)
        except Exception as exc:  # noqa: BLE001：留档失败绝不能拖垮识别
            self._rec = None
            self.record_path = ""
            self.record_error = f"录音留档打不开（{exc}）"

    def _write_record(self, mono: np.ndarray) -> None:
        rec = self._rec
        if rec is None:
            return
        try:
            rec.writeframes((np.clip(mono, -1.0, 1.0) * 32767.0).astype("<i2").tobytes())
            self.recorded_samples += int(mono.shape[0])
        except Exception as exc:  # noqa: BLE001
            self.record_error = f"录音写入失败（{exc}），已停止留档"
            self._close_recorder()

    def _close_recorder(self) -> None:
        rec = self._rec
        self._rec = None
        if rec is not None:
            try:
                rec.close()
            except Exception:  # noqa: BLE001
                pass

    def _reset_run_state(self) -> None:
        """新一轮采集开始时重置语音/语种状态（language 缓存保留）。"""
        self._last_voice_at = time.time()
        self._voice_observed = False
        self._last_probe_at = 0.0
        self._lang_votes = []
        self.stitcher.reset()

    def _close_stream(self) -> None:
        stream, self._stream = self._stream, None
        if stream is not None:
            try:
                stream.stop()
            except Exception:  # noqa: BLE001
                pass
            try:
                stream.close()
            except Exception:  # noqa: BLE001
                pass

    def _on_audio(self, indata, frames, time_info, status) -> None:  # noqa: ANN001
        """PortAudio (sounddevice) callback — must stay cheap, never raise."""
        if self._stop.is_set():
            return
        self.rx_blocks += 1
        self.last_audio_at = time.time()
        self._audio_q.put((indata.copy(), self.source_sr))

    def _on_loopback(self, in_data, frame_count, time_info, status):
        """PyAudioWPatch callback for the WASAPI loopback stream."""
        if self._stop.is_set():
            return (None, self._pa_mod.paComplete)
        self.rx_blocks += 1
        self.last_audio_at = time.time()
        block = np.frombuffer(in_data, dtype=np.float32)
        if self._lb_channels > 1:
            block = block.reshape(-1, self._lb_channels)
        self._audio_q.put((block.copy(), self.source_sr))
        return (None, self._pa_mod.paContinue)

    def record_thread_error(self, who: str, exc: BaseException) -> None:
        """把栈尾留下（最多 5 条）。线程死了不报错是最难查的故障，必须能看见。"""
        try:
            lines = traceback.format_exc().strip().splitlines()
        except Exception:  # noqa: BLE001
            lines = [repr(exc)]
        self.thread_error_log.append(f"[{who}] " + " ← ".join(
                                     ln.strip() for ln in lines[-4:]))
        if len(self.thread_error_log) > 5:
            del self.thread_error_log[:-5]

    def silent_seconds(self) -> float:
        """连续纯静音多久了（音频在进但电平一直不过门限）。"""
        base = self.last_sound_at or self.started_at
        return 0.0 if not base else max(0.0, time.time() - base)

    def decoding_age(self) -> float:
        """正在解的窗已经解了多少秒（0 = 当前没在解）。"""
        return 0.0 if not self.decoding_at else time.time() - self.decoding_at

    def stall_seconds(self, over: float = 8.0) -> float:
        """识别"挂死"的程度：同一窗解超过 over 秒还没回来，返回超出的秒数。

        GPU/CT2 调用挂死不抛异常，try 拦不住 —— 这是唯一能发现它的办法。
        """
        age = self.decoding_age()
        return 0.0 if age <= over else age - over

    def thread_alive(self) -> bool:
        """识别线程还活着吗 —— 状态行用它判断"字幕卡住"是不是线程死了。"""
        t = getattr(self, "_thread", None)
        return bool(t and t.is_alive())

    def _run(self) -> None:
        """识别线程的外层保险：任何一窗出错只丢那一窗，绝不许线程静默退出。

        线程一死，界面就永远停在最后一条字幕上且没有任何提示（用户看到的"字幕卡住"），
        所以这里计数、把异常写进 error 让界面显示，然后继续跑。
        """
        while not self._stop.is_set():
            try:
                self._run_loop()
            except Exception as exc:  # noqa: BLE001
                self.thread_errors += 1
                self.error = (f"识别线程异常（已跳过该窗，继续工作）："
                              f"{type(exc).__name__}: {exc}")
                self.record_thread_error("识别", exc)
                time.sleep(0.3)

    def _run_loop(self) -> None:
        """Decode/resample thread shared by both capture sources."""
        while not self._stop.is_set():
            try:
                block, sr = self._audio_q.get(timeout=0.2)
            except queue.Empty:
                self._update_hint()
                # VAD 探针：即使回环停止送包，也要靠"最近缓冲"判断语音是否已结束
                self._maybe_probe()
                # 关键：回环在语音停止后不再送新数据包，早触发必须在
                # "无数据"分支里也检查，否则停顿 flush 永远不会发生。
                self._maybe_early_flush()
                continue
            mono = block.mean(axis=1) if block.ndim > 1 else block.ravel()
            mono = mono.astype(np.float32, copy=False)
            # 轻量电平：让界面立刻知道"到底有没有声音进来"
            try:
                self.last_rms = float(np.sqrt(np.mean(np.square(mono, dtype=np.float64))))
            except Exception:  # noqa: BLE001
                pass
            # 语音活动判定的"当前来源"：VAD 可用时以 speech_end 为准（见
            # _transcribe），VAD 不可用（老后端/纯 mock）才退回 RMS。
            if self.last_rms >= self.silence_rms:
                self.last_sound_at = time.time()   # 有电平：刷新"最后一次有声"
            if (not self.vad_probe or not self._vad_supported) \
                    and self.last_rms >= self.silence_rms:
                self._voice_observed = True
                self._last_voice_at = time.time()
            mono = resample_to_16k(mono, sr)
            if mono.size == 0:
                continue
            self._write_record(mono)
            with self._lock:
                self._buffer.append(mono)
                self._buffered_samples += mono.shape[0]
                self._drop_oldest_locked()
            self._update_hint()
            self._maybe_probe()
            if not self._maybe_early_flush():
                self._drain_buffer(force=False)

    def _maybe_probe(self) -> None:
        """到点就跑一次探测级解码（VAD 语音段 + 语种漂移），不消费缓冲。"""
        if not self.vad_probe or not self.started_at:
            return
        if time.time() - self._last_probe_at < self.probe_interval:
            return
        self._run_probe()

    def _run_probe(self) -> None:
        self._last_probe_at = time.time()
        need = int(self.probe_len * TARGET_SR)
        with self._lock:
            if self._buffered_samples < int(TARGET_SR * 0.4):
                return
            joined = np.concatenate(self._buffer) if len(self._buffer) > 1 else (
                self._buffer[0] if self._buffer else np.zeros(0, np.float32))
            # 取最近 probe_len 秒尾部切片做探测（只读，不消费 buffer）
            clip = joined[-need:].copy() if joined.shape[0] >= need else joined.copy()
        if clip.shape[0] < int(TARGET_SR * 0.4):
            return
        # probe=True：模型输出仅用于更新语音活动时刻 + 语种投票
        self._transcribe(clip, 0.0, clip.shape[0] / TARGET_SR, probe=True)

    def _maybe_early_flush(self) -> bool:
        """语句停顿超过阈值且缓冲不满一窗：提前送检，压低感知延迟。"""
        if self.flush_after_silence <= 0 or not self.started_at:
            return False
        with self._lock:
            have = self._buffered_samples
        window = int(self.chunk_seconds * TARGET_SR)
        if (self._voice_observed
                and int(TARGET_SR * 0.5) <= have < window
                and time.time() - self._last_voice_at >= self.flush_after_silence):
            self._drain_buffer(force=True)
            return True
        return False

    def _update_hint(self) -> None:
        """没有数据流时给出可操作的中文提示（非致命）。"""
        if not self.started_at:
            return
        idle = time.time() - (self.last_audio_at or self.started_at)
        quiet = self.silent_seconds()
        if idle <= 3.0 and quiet > 8.0:
            # 数据在流、内容全静音 —— 99% 是"抓的不是发声的那个设备"
            self.hint = (
                f"音频一直在进，但连续 {quiet:.0f} 秒都是**纯静音**（电平 0）：你听到的声音"
                "没有进这条回环。两种常见原因：① 选的回环设备不是当前发声的设备 —— 看 "
                "Windows 音量图标里的输出设备名，在左侧换一个；② 播放器开了**独占/位完美"
                "输出**（WASAPI 独占模式下回环抓不到混音），关掉独占再试。")
        elif idle > 3.0 and self.rx_blocks == 0:
            if self.source == "system":
                self.hint = (
                    "该输出设备没有音频信号：确认声音真的在播，且浏览器输出到当前所选"
                    "回环设备（回环是按设备抓的，不是全局）。可在左侧换设备。"
                )
            else:
                self.hint = "麦克风没有数据：检查系统麦克风权限，或在左侧换设备。"
        elif idle > 3.0:
            self.hint = "已停止收到音频：可能已暂停播放或切换了输出设备。"
        else:
            self.hint = ""

    def _drop_oldest_locked(self) -> None:
        """模型跟不上时丢弃最旧音频，避免延迟无限增长。调用方需持锁。"""
        excess = self._buffered_samples - self.max_buffered_samples
        if excess <= 0:
            return
        remaining = excess
        while remaining > 0 and self._buffer:
            head = self._buffer[0]
            if head.shape[0] <= remaining:
                remaining -= head.shape[0]
                self._buffered_samples -= head.shape[0]
                self._consumed_samples += head.shape[0]
                self._buffer.pop(0)
            else:
                self._buffer[0] = head[remaining:]
                self._buffered_samples -= remaining
                self._consumed_samples += remaining
                remaining = 0
        self.dropped_samples += excess - remaining

    def _drain_buffer(self, *, force: bool) -> None:
        """Transcribe complete windows out of the rolling buffer."""
        window = int(self.chunk_seconds * TARGET_SR)
        while True:
            with self._lock:
                have = self._buffered_samples
                if have < window and not force:
                    return
                if have == 0:
                    return
                joined = np.concatenate(self._buffer)
                take = window if not force else have
                chunk = joined[:take]
                rest = joined[take:]
                self._buffer = [rest] if rest.size else []
                self._buffered_samples = rest.size
                start = self._consumed_samples / TARGET_SR
                self._consumed_samples += chunk.shape[0]

            self._transcribe(chunk, start, start + chunk.shape[0] / TARGET_SR)

    def _transcribe(self, chunk: np.ndarray, start: float, end: float,
                    *, probe: bool = False) -> None:
        """转写一个窗口。

        probe=True 时只做"探测"：用 VAD 语音段更新最后说话时刻、用检测结果
        给语种投票，**不产字幕、不过静音门**（探测窗口本身可能就全是 BGM/静音，
        它的价值恰恰是告诉我们"现在没有语音"）。
        """
        rms = float(np.sqrt(np.mean(np.square(chunk, dtype=np.float64)))) if chunk.size else 0.0
        if not probe:
            self.last_rms = rms
            if chunk.size < TARGET_SR * 0.4 or rms < self.silence_rms:
                return
        # 钉定前：窗口自由检测（第一声即定语种）；钉定后：正式窗口用钉定语种
        # （省每窗检测），探测窗口始终 None（它是语种漂移的雷达）。
        if self.language is None or (probe and self._auto_language):
            lang_for_model = None
        else:
            lang_for_model = self.language
        # 看门狗：记下"正在解哪一窗"。CT2/CUDA 是 C++ 阻塞调用，挂死时**不抛异常**，
        # 只能靠"线程活着但毫无进展"来发现（界面据此直接说卡在几秒处的窗）。
        self.decoding_span = (round(start, 1), round(end, 1))
        self.decoding_probe = bool(probe)
        self.decoding_at = time.time()
        try:
            result = self.model.transcribe(
                chunk,
                language=lang_for_model,
                fp16=False,
                verbose=None,  # whisper 的怪癖：False 反而会显示进度条，None 才全静默
                condition_on_previous_text=False,
                initial_prompt=self.initial_prompt or None,
                # 交给适配器按"本窗实际语种"决定要不要转：自动模式下钉了 zh
                # 也可能中途翻日，语种是窗口相对的事，不能在这儿一票定生死。
                simplify=self.simplify,
            )
        except Exception as exc:  # noqa: BLE001
            if not probe:
                self.error = f"识别失败：{exc}"
            return
        finally:
            self.decoding_at = 0.0     # 无论正常/异常/提前 return，都不算"在解"了

        if not isinstance(result, dict):  # 老式 openai-whisper 直连兼容
            result = {"text": (getattr(result, "text", "") or "").strip()}
        # text 必须是字符串：否则后面 join/split 会把整条线程带进沟里
        if not isinstance(result.get("text"), str):
            result = dict(result, text=str(result.get("text") or ""))
        # ② VAD 语音活动：窗口末尾仍有语音段 → 刷新最后说话时刻。
        #    （BGM 场景由探测窗口说了算，RMS 不再参与，见 _run。）
        speech_end = result.get("speech_end")
        if "speech_end" in result:
            self._vad_supported = True
        try:
            window_len = chunk.shape[0] / TARGET_SR
            if speech_end is not None and float(speech_end) >= window_len - 0.35:
                self._voice_observed = True
                self._last_voice_at = time.time()
        except (TypeError, ValueError):   # 适配器给了怪值也不该带走整条线程
            pass
        # ③ 语种投票（含自动重钉/漂移切换）
        self._vote_language(result)

        if probe:
            return

        # 一条字幕 = 一行原文：模型或多段拼接偶尔吐换行，压成空格，否则悬浮窗
        # 与 SRT 会把同一句拆成两行显示。
        text = " ".join((result.get("text") or "").split())
        if self.simplify:
            # 适配器一般已经转过；这里再兜一层（幂等）。判定顺序：本窗语种 →
            # 钉定语种 → 最近检测；日文一律不进（同形字会被改坏）。
            win = result.get("language") or self.language or self.detected_language
            if is_chinese_lang(win):
                text = to_simplified_if_chinese(text)   # 混假名（其实是日文）就不动
        if not text or text in _FILLER_TEXTS:
            self.empty_windows += 1     # 过了静音门却没字：过滤可疑
            self._maybe_unfilter_vad(rms)
            return
        self.empty_windows = 0
        self.processed_chunks += 1
        with self._lock:
            self._seq += 1
            caption = Caption(
                index=self._seq,
                start=start,
                end=end,
                text=text,
                wall_clock=time.time(),
            )
        # 半句缝合可能把它并回上一条：届时发布的是"同一条目号的修订版"
        self._results.put(self.stitcher.offer(caption))

    def _maybe_unfilter_vad(self, rms: float) -> None:
        """BGM 盖住语音时的自救：连续几窗「有音量但零字」就把非语音过滤关掉。

        Silero VAD + no_speech_prob 在强背景音乐下会把整段中文语音判成非语音 ——
        实测 243s、电平 0.16 的音频只吐 16 个字，界面还毫无提示（看着就是「卡住」）。
        """
        if (self.empty_windows < 3 or self.filter_disabled
                or not self.auto_unfilter or rms < self.silence_rms
                or not getattr(self.model, "supports_vad_toggle", False)):
            return
        try:
            self.model.set_non_speech_filter(False)
        except Exception:  # noqa: BLE001
            return
        self.filter_disabled = True
        self.empty_windows = 0
        self.notice = ("有音量却连续几窗零字：语音被「非语音过滤」（VAD / no_speech_prob）"
                       "判成了背景噪声，已自动关掉该过滤继续识别。")
        self.notice_at = time.time()

    def _vote_language(self, result: dict) -> None:
        """自动检测模式下的语种投票：宁可不钉，也不钉错。

        三条规矩都来自真实故障：
        ① 静音窗里 Whisper 会幻觉出「日本語字幕」并自报高置信 ja —— 一票就能把中文
           音频钉成日语，之后整场都用日语解码，出来的就是错乱。所以**没有有效文本就不投票**。
        ② 文字脚本 > 模型自评：出现假名就一定不是中文（多高的置信度都不抢）；「汉字无
           假名」日语也可能长这样，所以模型自报不到 0.90 才让脚本把语种纠回 zh。
           真日语的自评常常只有 0.5 —— 计数门槛压到 0.45，否则正确的票被整张丢掉，
           语种就一直停在错的那边（"日语到中文不准确"的根因）。
        ③ 冷启动要 2 票一致才钉；中文↔日语之间切换要 3 票（最容易互翻的一对）。

        用户显式选定语种（_auto_language=False）时完全忽略本函数。
        """
        if not self._auto_language:
            return
        text = " ".join((result.get("text") or "").split())
        if is_hallucinated(text):
            return
        declared = (result.get("language") or "").strip() or None
        prob = result.get("language_probability")
        prob = 1.0 if prob is None else float(prob)
        script = script_language(text)
        lang, conf = declared, prob
        if script and (script != declared or not declared):
            # 假名是中文里绝不会出现的硬证据，任何置信度都直接判日语；
            # 「汉字无假名」日语也可能长这样，模型自报不到 0.90 才让脚本抢。
            if script == "ja" or not declared or prob < _SCRIPT_OVERRIDES_ZH:
                lang, conf = script, _SCRIPT_CONF
        if not lang or conf < _VOTE_MIN_CONF:
            return
        self.detected_language = str(lang)
        prev = self.language
        if prev == lang:
            self._lang_votes = []
            return
        need = 3 if prev is not None and {prev, lang} == _CJK_PAIR else 2
        # 只数"连续"票：夹进别的语种立刻清零（防 A/B/A 抖动凑票）
        if self._lang_votes and self._lang_votes[-1] != lang:
            self._lang_votes = []
        votes = self._lang_votes + [lang]
        if len(votes) >= need:
            self.language = lang
            self._lang_votes = []
            if prev is not None:
                self.language_switches += 1
                name = _LANG_NAMES.get(lang, lang)
                self.notice = f"语种自动切换：{name}（{lang}）"
                self.notice_at = time.time()
        else:
            self._lang_votes = votes


def list_loopback_devices() -> dict[int, str]:
    """Return ``{device_index: name}`` for every WASAPI loopback endpoint."""
    out: dict[int, str] = {}
    try:
        import pyaudiowpatch as pyaudio

        pa = pyaudio.PyAudio()
        try:
            for info in pa.get_loopback_device_info_generator():
                out[int(info["index"])] = str(info["name"])
        finally:
            pa.terminate()
    except Exception:  # noqa: BLE001
        return {}
    return out


def pick_loud_loopback_device(
    probe_seconds: float = 1.2,
    threshold: float = 0.002,
) -> tuple[int | None, dict[int, float]]:
    """自动挑选「当前真的有声音」的回环设备。

    WASAPI loopback 是按输出设备抓的：如果视频走的是另一个设备，抓默认设备就
    会是纯静音。这里并发短暂探测每个回环设备的电平，返回电平最高的设备。

    返回 ``(device_index | None, {index: peak})``。全为静音时返回 ``(None, peaks)``。
    """
    peaks: dict[int, float] = {}
    try:
        import pyaudiowpatch as pyaudio
    except Exception:  # noqa: BLE001
        return None, peaks

    pa = pyaudio.PyAudio()
    results: dict[int, float] = {}
    lock = threading.Lock()

    try:
        devices = [
            (int(d["index"]), d)
            for d in pa.get_loopback_device_info_generator()
            if int(d.get("maxInputChannels") or 0) > 0
        ]
    except Exception:  # noqa: BLE001
        pa.terminate()
        return None, peaks

    default_idx: int | None = None
    try:
        default_idx = int(pa.get_default_wasapi_loopback()["index"])
    except Exception:  # noqa: BLE001
        pass

    def probe(idx: int, info) -> None:
        holder = {"peak": 0.0, "blocks": 0}

        def cb(in_data, frame_count, time_info, status):
            arr = np.frombuffer(in_data, dtype=np.float32)
            if arr.size:
                peak = float(np.abs(arr).max())
                if peak > holder["peak"]:
                    holder["peak"] = peak
                holder["blocks"] += 1
            return (None, pyaudio.paContinue)

        stream = None
        try:
            rate = int(info["defaultSampleRate"] or 48_000)
            channels = int(info["maxInputChannels"] or 1)
            stream = pa.open(
                format=pyaudio.paFloat32,
                channels=channels,
                rate=rate,
                input=True,
                input_device_index=idx,
                frames_per_buffer=int(rate * 0.1),
                stream_callback=cb,
            )
            stream.start_stream()
            time.sleep(probe_seconds)
        except Exception:  # noqa: BLE001
            pass
        finally:
            if stream is not None:
                try:
                    stream.stop_stream()
                except Exception:  # noqa: BLE001
                    pass
                try:
                    stream.close()
                except Exception:  # noqa: BLE001
                    pass

        with lock:
            results[idx] = holder["peak"]

    threads = [threading.Thread(target=probe, args=(i, d), daemon=True) for i, d in devices]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=probe_seconds + 3.0)
    pa.terminate()

    peaks.update(results)
    if not peaks:
        return None, peaks

    best = max(peaks, key=lambda k: peaks[k])
    if peaks[best] < threshold:
        # 全静音：优先交回默认设备，让引擎自己给出"无信号"提示。
        return default_idx, peaks
    return best, peaks


def to_srt(captions: list[Caption]) -> str:
    """Render captions as an SRT subtitle document (timed from session start)."""

    def stamp(seconds: float) -> str:
        ms = int(round(max(0.0, seconds) * 1000))
        h, ms = divmod(ms, 3_600_000)
        m, ms = divmod(ms, 60_000)
        s, ms = divmod(ms, 1000)
        return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

    lines: list[str] = []
    for i, cap in enumerate(captions, start=1):
        lines.append(str(i))
        lines.append(f"{stamp(cap.start)} --> {stamp(cap.end)}")
        lines.append(cap.text)
        lines.append("")
    return "\n".join(lines)
